### ISSUE TITLE
name ... again

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-ramel#50]
## TODOs
 - [x] Update `@@kst` actions prefix
 - [x] Update github repo
 - [x] Update link to coveralls
 - [x] Update link to circleCI (should be automated)
 - [ ] Update link to greenkeeper
 - [x] Update badges
 - [x] Update documentation
 - [x] Update todomvc (comments)

--

@delphinemillet @guillaumecrespel @bpetetot @frinyvonnick @EmrysMyrddin @AFaugeras @Taranys @Okazari 

Hi !

I just changed the name on github.
But I am not fan of this once again.

@delphinemillet said it could be cool to have `food` name since the organisation is `alakarte(io)`. An I think it's great.

What your tough about it ?
Should we find a name related to food or keep k-rex ?

Vote k-rex: ❤️
Or vote for food name: 👍 
-> If you have food name idea feel free to respond to this thread.

**Comment by bpetetot** [comment]
I like `k-melon`, `k-milk` or `k-lemon` but only because it sounds good, no other reason.

Nothing about food, but a great name could be : `k-söze` do you have the reference ? :D

**Comment by Taranys** [comment]
I suggest `k-ouign-amann` but I can be hard to write for to none Breton people 😉 

Maybe use pastrie names like `k-upcake`, `k-ouglof` or `k-ookie`

**Comment by guillaumecrespel** [comment]
I think the `k` must get along. For example `k-soulet`, `k-cahuete`, `k-féine`,...

**Comment by EmrysMyrddin** [comment]
I like k-feine :-)

**Comment by Okazari** [comment]
I love the way @Taranys do some puns like @guillaumecrespel but in english ;). I feel this is a lot more approachable in a english world like our.

**Comment by guillaumecrespel** [comment]
`alakarte` it's for the frenchy touch, same for my proposal. You think it's complicated to understand ?

**Comment by Okazari** [comment]
Although i feel that `alakarte` is a great name to work in france, i feel that shared libraries may need to have a name that touch a larger audience. Otherwise, why are we talking english here ? ;)

**Comment by fabienjuif** [comment]
I agree with @Okazari 
(`alakarte` is not only understood by french but by anglophones too: https://www.linguee.fr/francais-anglais/traduction/services+%C3%A0+la+carte.html)

The best should be that the pun is understandable by both. Like `k-ookie`

**Comment by frinyvonnick** [comment]
Why not `k-ffeine` as suggested but with two f so english people understand it too ?

**Comment by guillaumecrespel** [comment]
everybody know cassoulet !! no ? 😄
it's the best french meal => https://www.france-hotel-guide.com/fr/blog/15-plats-francais-a-essayer-absolument/
but ok, i understand !

**Comment by Okazari** [comment]
I love `k-upcake` because it's a simple/small pastry :) i feel it goes in the direction of the library values

**Comment by fabienjuif** [comment]
It goes the same with `k-ookie`
And I prefer to eat cookies

**Comment by guillaumecrespel** [comment]
The only problem is you can't hear the `k`.
`k-rambar`, `k-ramel` ?

**Comment by fabienjuif** [comment]
- `k-rambar`: I don't know if this is smart for us to use a trademark
 - `k-ramel`: sounds nice but are anglophones familiar with this ?

**Comment by frinyvonnick** [comment]
Yes they use caramel or fudge 👍

**Comment by EmrysMyrddin** [comment]
For `k-ffeine`, it works in frensh but not in english, the letter `k` doesn't produce the sound `ca`... :-)

**Comment by fabienjuif** [comment]
Time to vote:
 - `k-ramel` : 👍 
 - `k-rrot` : 😄 

Until tomorrow evening: @delphinemillet @guillaumecrespel @bpetetot @frinyvonnick @EmrysMyrddin @AFaugeras @Taranys @Okazari

**Comment by fabienjuif** [comment]
I am waiting for the next greenkeeper PR to close this issue

**Comment by fabienjuif** [comment]
https://github.com/alakarteio/k-ramel/pulls?q=is%3Apr+is%3Aclosed
